# Generated by Django 4.2.7 on 2025-10-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('category', models.CharField(choices=[('COMFORT', 'Confort'), ('SECURITY', 'Sécurité'), ('CONNECTIVITY', 'Connectivité'), ('EXTERIOR', 'Extérieur')], max_length=20, verbose_name='Catégorie')),
                ('properties', models.ManyToManyField(blank=True, related_name='amenities', to='properties.property', verbose_name='Propriétés')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['category', 'name'],
            },
        ),
    ]
