# Generated by Django 4.2.7 on 2025-10-15 07:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.CharField(choices=[('HOUSE', 'Maison'), ('APARTMENT', 'Appartement'), ('STUDIO', 'Studio'), ('ROOM', 'Chambre')], max_length=20, verbose_name='Type')),
                ('surface', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface (m²)')),
                ('number_of_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de pièces')),
                ('number_of_bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de chambres')),
                ('number_of_bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de salles de bain')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Étage')),
                ('furnished', models.BooleanField(default=False, verbose_name='Meublé')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Charges')),
                ('charges_included', models.BooleanField(default=False, verbose_name='Charges incluses')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caution')),
                ('agency_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Frais d'agence")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('PUBLISHED', 'Publié'), ('RENTED', 'Loué'), ('DELETED', 'Supprimé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('view_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/%d/', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/%Y/%m/%d/', verbose_name='Miniature')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='properties.property', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', '-created_at'], name='properties__status_5b95bb_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord', 'status'], name='properties__landlor_11e4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['type', 'status'], name='properties__type_d3d96a_idx'),
        ),
    ]
