# Generated by Django 4.2.7 on 2025-10-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('VISITOR', 'Visiteur'), ('TENANT', 'Locataire'), ('LANDLORD', 'Propriétaire'), ('ADMIN', 'Administrateur')], default='TENANT', max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('DELETED', 'Supprimé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
